config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"
  post "/tasks", to: "tasks#create"
  get "/tasks/new", to: "tasks#new", as: :newtask
  get "/tasks/:id", to: "tasks#show", as: :task
  get "/tasks/:id/edit", to: "tasks#edit", as: :edittask
  patch "/tasks/:id", to: "tasks#update"
  delete "/tasks/:id", to: "tasks#destroy"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Return to task list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><% if task.completed? %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task.id) %>
        <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
</ul>

<%= link_to "Add a task", newtask_path %>

app/views/tasks/new.html.erb
<h1>Add Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>


<%= link_to "Return to task list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>

<%= link_to edittask_path(@task.id), class: 'btn btn-light btn-sm border' do %>
      <i class="fa fa-pencil"></i> Edit this task
    <% end %>

<% if @task.completed %>
    <i class="fa fa-check-square-o"></i> <p><strong>This task is completed</strong></p>
  <% else %>
    <i class="fa fa-square-o"></i> <p><strong>This task is not completed yet</strong></p>
  <% end %>

<p><%= link_to "Return to task list", tasks_path %></p>